version: '3.8'

services:
  web:
    build: .
    command: gunicorn movie_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:7

  celery:
    build: .
    command: celery -A movie_project worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  media:
